---
title: "PLSR for N and ADF with all data"
author: "Jayan Wijesingha"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  ioslides_presentation:
    css: iso_css.css
    self_contained: no
    incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(data.table)
library(dplyr)
library(hsdar)
library(ggplot2)
library(caret)
library(purrr)
library(readr)
library(ppls)
library(tibble)
library(MASS)
```

```{r read data, include=FALSE, warning=FALSE, error=FALSE, message = FALSE}

# Reading data tables

## Read WIZ data

wiz_df <- read.csv("./output_wiz/hs_all_nrm_df_wiz.csv", header = TRUE)
wiz_df$source <- rep("Witzenhausen", dim(wiz_df)[1])

## Read Rhön data

dsb_df <- read.csv("./output_dsb/hs_all_nrm_df_dsb.csv", header = TRUE)
dsb_df$source <- rep("Rhön", dim(dsb_df)[1])

## merging two data sets

all_df <- rbind(wiz_df, dsb_df)

```

# Splitting Data for train and test

```{r prep data, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE, comment=" "}

set.seed(777)

table(all_df$field_id) # Check exisisting data rows based on field id

## Separate data set in to two groups with same propotion from each group (60%)
split_sample <- groupdata2::partition(all_df, p = 0.8, cat_col = "field_id", 
                                      num_col = NULL, id_col = NULL, 
                                      id_aggregation_fn = sum, 
                                      force_equal = FALSE, list_out = F)

## Subset to train data (1)
train_df <- split_sample %>% dplyr::filter(.partitions == 1) %>% data.frame()
table(train_df$field_id)

## Subset to train data (2)
test_df <- split_sample %>% dplyr::filter(.partitions == 2) %>% data.frame()
table(test_df$field_id)

## Coulmn index for estimators (independent variables)
estimators <- c(5:122)

## Coulmn index for each targets (dependent variables)
targetN <- 130
targetADF <- 133
```



```{r calibration, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE}
# 3. Model calibration (training)

# loading calibrated model
load("./output/models/plsr_model_for_N_ADF.RData")

pls_all_compare <- resamples(list("N_PLS" = pls_all_n,
                                  "ADF_PLS" = pls_all_adf))
```

# Model calibration for N (training)

## PLSR

```{r calibration_out_n, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="60%", comment=" "}

par(mfrow=c(1,2))
plot(pls_all_n, main = "N (%) estimation model with PLSR \n Tuning with Ncomp")
plot(varImp(pls_all_n), 10, main = "N (%) estimation model with PLSR \n Important variables for prediction")
par(mfrow=c(1,1))
```

# Model calibration for ADF (training)

## PLSR

```{r calibration_out_adf, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="60%", comment=" "}
par(mfrow=c(1,2))
plot(pls_all_adf, main = "ADF (%) estimation model with PLS \n Tuning with Ncomp")
plot(varImp(pls_all_adf), 10, main = "ADF (%) estimation model with PLS \n Important variables for prediction")
par(mfrow=c(1,1))
```

# Model calibration - Comparision (N vs ADF)

```{r calibration_out_nadf, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="65%", comment=" "}

bwplot(pls_all_compare, scales=list(tck=c(1,0), x=list(cex=1.5), y=list(cex=1.5)))
```

```{r validation, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE}
source("./obs_pred_plot.R")
```

# Model validation for N (testing)

```{r validation_out_n, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="60%", comment=" "}

obs_pred_plot(pls_all_n, test_df, 
              estimators, targetN, plot = TRUE, 
              title = "N (%) estimation model with PLSR")

```

# Model validation for ADF (testing)

```{r validation_out_adf, echo=FALSE, include=TRUE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="60%", comment=" "}

obs_pred_plot(pls_all_adf, test_df, 
              estimators, targetADF, plot = TRUE, 
              title = "ADF (%) estimation model with PLSR")

```
