---
title: 'Select train/test data based on changing seed'
author: "Jayan Wijesingha"
date: "15 February 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(data.table)
library(dplyr)
library(hsdar)
library(ggplot2)
library(caret)
library(purrr)
library(readr)
library(ppls)
library(tibble)
library(MASS)
library(knitr)
library(kableExtra)
```

```{r read_data, include=FALSE, warning=FALSE, error=FALSE, message = FALSE}

# Reading data tables

## Read WIZ data

wiz_df <- read.csv("./output_wiz/hs_all_nrm_df_wiz.csv", header = TRUE)
wiz_df$source <- rep("Witzenhausen", dim(wiz_df)[1])

## Read Rhön data

dsb_df <- read.csv("./output_dsb/hs_all_nrm_df_dsb.csv", header = TRUE)
dsb_df$source <- rep("Rhön", dim(dsb_df)[1])

## merging two data sets

all_df <- rbind(wiz_df, dsb_df)
all_df$row <- c(1:nrow(all_df))
```

# Original group propotions

```{r seed, echo=FALSE}
all_df %>% 
  count(field_id) %>% 
  kable(align='c')
```

# Code for data partiotion

```{r seedvec, echo=TRUE, warning=FALSE, error=FALSE, message = FALSE}
train_list <- vector("list",5) 
test_list <- vector("list",5)
seed_vec <- c(1, 777, 1985, 37213, 104895)
```



```{r seed1, echo=TRUE}

for (k in 1:length(seed_vec)){
  set.seed(seed_vec[k])
  
  split_sample <- groupdata2::partition(all_df, p = 0.75, cat_col = "field_id", 
                                      num_col = NULL, id_col = NULL, 
                                      id_aggregation_fn = sum, 
                                      force_equal = FALSE, list_out = F)
  train_list[[k]] <- split_sample %>% dplyr::filter(.partitions == 1) %>% data.frame()
  test_list[[k]] <- split_sample %>% dplyr::filter(.partitions == 2) %>% data.frame()
  test_list[[k]]$seed <- rep(seed_vec[k], dim(test_list[[k]])[1])
}
```

# Propotion of partioned data

```{r seed2, echo=TRUE, warning=FALSE, error=FALSE, message = FALSE}
for (z in 1:length(seed_vec)) {
  print(sprintf("Seed value: %i", seed_vec[z]))
  print(table(test_list[[z]]$field_id))
  print("\n")
}

```


# Summary of the selected test data

```{r seed3, warning=FALSE, error=FALSE, message = FALSE}
out_test_df <- test_list[[1]][c(137,135,1)]

for (j in 2:length(seed_vec)){
  out_test_df <- cbind(out_test_df, test_list[[j]][c(137,135,1)])
}
names(out_test_df) <- c("seed", "row", "field", "seed", "row", "field", "seed", "row", 
"field", "seed", "row", "field", "seed", "row", "field")

out_test_df %>% 
  kable("latex", booktabs = T) %>%
  kable_styling(latex_options = "striped", position = "center", full_width = T) %>%
  row_spec(0, bold = T) %>%
  column_spec(c(1,4,7,10,13), bold = T, color = "blue")

```




