---
title: "Data summary for WIZ"
author: "Jayan Wijesingha"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(digits = 3)

library(data.table)
library(dplyr)
library(hsdar)
library(ggplot2)
library(caret)
library(purrr)
library(readr)
library(ppls)
library(tibble)
library(kableExtra)

windowsFonts(Helvetica=windowsFont("Helvetica-Regular"))
```

# 1. Summary of the grasslands


```{r grassland info, echo=FALSE, results='asis'}

gl_df <- data.frame(
  field_id = c("G1a", "G1b", "G2", "G3"),
  area = c("Meißner", "Meißner", "Werrau", "Hebenshausen"),
  mowing_freq = c(1, 1, 2, 3),
  veg_type = c(
  "Geranio sylvatici-Trisetetum flavescentis (R.Knapp ex Oberd. 1957)",
  "Polygalo-Nardetum strictae (Oberd. 1957)",
  "Plantagini lanceolatae-Festucetum rubrae meadow",
  "Seeded grassland dominated by *Lolium perenne* and *Poa trivialis*"
  ),
  desc = c(
  "Nature conservation grassland, dry, late harvest, no fertilisation",
  "Nature conservation grassland, wet, late harvest, no fertilisation",
  "Extensive grassland at a riverside, no fertilisation",
  "Intensive grassland, fertilised"
  )
  )

kable(gl_df, col.names = c("Field ID", "Area", "No. of Mowings", "Vegetation Type", "Note"),
      caption = "Details of the grasslands") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)

```

```{r harvest info, echo=FALSE, results='asis'}
harverst_df <- data.frame(field_id = c("G1a", "G1b", "G2", "G2","G3", "G3", "G3"),
                          harvest_no = c("H1", "H1", "H1", "H2", "H1", "H2", "H3"),
                          harvest_date = as.Date(c("2018-07-13", "2018-07-14", "2018-05-28", "2018-09-24", "2018-05-10", "2018-06-06", "2018-08-01")),
                          harvest_date_doy = format(as.Date(c("2018-07-13", "2018-07-14", "2018-05-28", "2018-09-24", "2018-05-10", "2018-06-06", "2018-08-01")), "%j"))

kable(harverst_df[,c(2:4)], col.names = c("Harvest No.", "Harvest Date", "Harvest Date (DOY)"),
      caption = "Mowing detials of the grasslands") %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  group_rows("G1a", 1, 1) %>%
  group_rows("G1b", 2, 2) %>%
  group_rows("G2", 3, 4) %>%
  group_rows("G3", 5, 7)
```
# 2. Filed data (biomass, N, and, ADF)

## Biomass data

```{r bm data, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%"}
bm_list <- dir(path = "./input_wiz/bm/", pattern = "*.csv", full.names = TRUE)

bm_data <- bm_list %>%
  map(read_csv) %>%    # read in all the files individually, using
  # the function read_csv() from the readr package
  reduce(rbind)     # reduce with rbind into one dataframe


bm_data$logdb <- log(bm_data$db) # Standardise dry biomass with log transformation
bm_data$doy <- factor(bm_data$doy)

### Histogram plot for dry biomass data
ggplot(bm_data, aes (x = doy, y = db, fill = field_id)) + 
  geom_boxplot(alpha = 0.8) +
  #facet_grid(. ~ field_id, 
             #labeller = labeller(field_id = c(g1 = "G1", g2 = "G2", g3 = "G3", g4 = "G4"))) +
  theme_bw(base_size = 12, base_family = "Lucida") +
  scale_fill_manual(values = c("#3CA437", "#B1740F", "#D5006A", "#17377A"),
                    name = "Grassland ID", 
                    labels = c("G1a", "G1b", "G2", "G3")) +
  labs(y = "Dry biomass (kg/m²)",
       x = "Julian date (DOY)",
       caption = "Dry biomass data (WIZ)") +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.caption = element_text(size = 11, face = "italic", hjust = 1),
    legend.position = "bottom"
  )
```

## Nitrogen (N) data

```{r cn data, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%"}
cn_data <- read.csv("./input_wiz/cn/grassland_cn.csv", header = TRUE)
cn_data$doy <- factor(cn_data$doy)

### Histogram plot for N concentration data
ggplot(cn_data, aes (x = doy, y = n, fill = field_id)) + 
  geom_boxplot(alpha = 0.75) +
  theme_bw(base_size = 12, base_family = "Lucida") +
  scale_fill_manual(values = c("#3CA437", "#B1740F", "#D5006A", "#17377A"),
                    name = "Grassland ID", 
                    labels = c("G1a", "G1b", "G2", "G3")) +
  labs(x = "Julian date (DOY)",
       y = "N (%) per dry matter",
       caption = "Nitrogen (N) concentration data (WIZ)") +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.caption = element_text(size = 11, face = "italic", hjust = 1),
    legend.position = "bottom"
  )

# ### Histogram plot for C concentration data
# ggplot(cn_data, aes (x = c, fill= field_id)) + 
#   geom_density(alpha = 0.4) +
#   facet_grid(. ~ harvest) +
#   theme_bw(base_size = 12, base_family = "Lucida") +
#   scale_fill_manual(values = c("#3CA437", "#B1740F", "#D5006A", "#17377A"),
#                     name = "Grassland ID", 
#                     labels = c("G1", "G2", "G3", "G4")) +
#   labs(x = "C (%) per dry matter",
#        y = "Density",
#        caption = "Carbon (C) concentration data (WIZ)") +
#   theme(
#     axis.text = element_text(size = 12),
#     axis.title = element_text(size = 14),
#     plot.caption = element_text(size = 11, face = "italic", hjust = 1),
#     legend.position = "bottom"
#   )
```

## Acid detergent fiber (ADF) data

```{r adf data, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%"}
adf_data <- read.csv("./input_wiz/adf/grassland_adf2.csv", header = TRUE)
adf_data$doy <- factor(adf_data$doy)

### Histogram plot for ADF concentration data
ggplot(adf_data, aes (x = doy, y = adf, fill = field_id)) + 
  geom_boxplot(alpha = 0.8) +
  theme_bw(base_size = 12, base_family = "Lucida") +
  scale_fill_manual(values = c("#3CA437", "#B1740F", "#D5006A", "#17377A"),
                    name = "Grassland ID", 
                    labels = c("G1a", "G1b", "G2", "G3")) +
  labs(x = "Julian date (DOY)",
       y = "ADF (%) per dry matter",
       caption = "Acid detergent fiber (ADF) concentration data (WIZ)") +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.caption = element_text(size = 11, face = "italic", hjust = 1),
    legend.position = "bottom"
  )
```

## N vs ADF

```{r n vs adf data, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%"}

ggplot(merge(adf_data, cn_data) %>% tidyr::drop_na(), 
       aes (x = n, y = adf)) +
  geom_point(aes(col = field_id), alpha = 0.6, size = 5, shape = 20) +
  stat_smooth(method=lm, se = FALSE, linetype = "twodash") +
  #facet_grid(. ~ harvest) + 
  coord_fixed(ratio = 0.15) +
  theme_bw(base_size = 12, base_family = "Lucida") +
  scale_color_manual(values = c("#3CA437", "#B1740F", "#D5006A", "#17377A"),
                    name = "Grassland ID", 
                    labels = c("G1a", "G1b", "G2", "G3")) +
  labs(x = "N (%) per dry matter",
       y = "ADF (%) per dry matter",
       caption = "Nitrogen (N) vs Acid detergent fiber (ADF) data (WIZ)") +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.caption = element_text(size = 11, face = "italic", hjust = 1),
    legend.position = "bottom"
  )
```

```{r hs data, include=FALSE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%"}
## Hyperspectral data

hs_list <- dir(path = "./input_wiz/hs/", pattern = "*.csv", full.names = TRUE)

hs_read <- hs_list %>%
  map(read_csv) %>%    
  reduce(rbind) 

### Remove unwanted wavelength bands (450 - 478 nm & 950 - 998 nm)
hs_data <- hs_read[-c(5:12, 131:142)]

# 2. Merging and removing NAs

## hyperspectral and biomass

hs_bm_df <- merge(bm_data, hs_data) %>% tidyr::drop_na()

## hyperspectral and nitrogen

hs_cn_df <- merge(cn_data, hs_data) %>% tidyr::drop_na()

## hyperspectral and adf

hs_adf_df <- merge(adf_data, hs_data) %>% tidyr::drop_na()

## all three tables

hs_all_df <- merge(hs_data, merge(bm_data, merge(cn_data, adf_data))) %>% tidyr::drop_na()
hs_all_df$field_id <- factor(hs_all_df$field_id)
hs_all_df$harvest <- factor(hs_all_df$harvest)
```

# 3. Hyperspectral data

```{r speclib data, echo=FALSE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%", comment=" "}

wv <- seq(482, 950, 4)
spec_df <- hs_all_df[c(5:122)] # Select only spectral data
spec_org_mat <- as.matrix(spec_df)/10000 # Convert df to a matrix
spec_nrm_mat <- t(apply(spec_org_mat, 1, normalize.vector)) # Normalise each row


## Speclib data for original reflectance
spec_org_data <- speclib(spec_org_mat, wv)
SI(spec_org_data) <- hs_all_df[c(1:4, 123:134)]
#spec_org_data

## Speclib data for normalised reflectance
spec_nrm_data <- speclib(spec_nrm_mat, wv)
SI(spec_nrm_data) <- hs_all_df[c(1:4, 123:134)]
spec_nrm_data

### Convert normalised reflectance back to a dataframe
source("./funs/spc_2df.R")
hs_all_nrm_df <- spc_2df(spec_nrm_data)
hs_all_nrm_df <- hs_all_nrm_df[c(1:4, 17:134, 5:16)] # arrange columns
names(hs_all_nrm_df) <- names(hs_all_df)

## Plotting mean spectral curves for Harvest level and grassland level

### First Harvest
par(mfrow=c(1,2))

plot(subset(spec_org_data, field_id == "g1" & harvest == "H1"), FUN = "mean", col = "#3CA437", 
     main = "Original Reflectance - H1", ylim=c(0,0.7))
plot(subset(spec_org_data, field_id == "g2" & harvest == "H1"), FUN = "mean", col = "#B1740F", new = FALSE)
plot(subset(spec_org_data, field_id == "g3" & harvest == "H1"), FUN = "mean", col = "#D5006A", new = FALSE)
plot(subset(spec_org_data, field_id == "g4" & harvest == "H1"), FUN = "mean", col = "#17377A", new = FALSE)
legend("topleft", legend = c("G1a", "G1b", "G2", "G3"),
       col = c("#3CA437", "#B1740F", "#D5006A", "#17377A"), lty=1)


plot(subset(spec_nrm_data, field_id == "g1" & harvest == "H1"), FUN = "mean", col = "#3CA437", 
     main = "Normalised Reflectance - H1", ylim=c(0,0.2))
plot(subset(spec_nrm_data, field_id == "g2" & harvest == "H1"), FUN = "mean", col = "#B1740F", new = FALSE)
plot(subset(spec_nrm_data, field_id == "g3" & harvest == "H1"), FUN = "mean", col = "#D5006A", new = FALSE)
plot(subset(spec_nrm_data, field_id == "g4" & harvest == "H1"), FUN = "mean", col = "#17377A", new = FALSE)
legend("topleft", legend = c("G1a", "G1b", "G2", "G3"),
       col = c("#3CA437", "#B1740F", "#D5006A", "#17377A"), lty=1)


### Two cuts system

plot(subset(spec_org_data, field_id == "g3" & harvest == "H1"), FUN = "mean", col = "darkgreen", 
     main = "Original Reflectance - G2", ylim=c(0,0.7))
plot(subset(spec_org_data, field_id == "g3" & harvest == "H2"), FUN = "mean", col = "#6B244C", new = FALSE)
legend("topleft", legend = c("H1", "H2"),
       col = c("darkgreen", "#6B244C"), lty=1)


plot(subset(spec_nrm_data, field_id == "g3" & harvest == "H1"), FUN = "mean", col = "darkgreen", 
     main = "Normalised Reflectance - G2", ylim=c(0,0.2))
plot(subset(spec_nrm_data, field_id == "g3" & harvest == "H2"), FUN = "mean", col = "#6B244C", new = FALSE)
legend("topleft", legend = c("H1", "H2"),
       col = c("darkgreen", "#6B244C"), lty=1)


### Three cuts system

plot(subset(spec_org_data, field_id == "g4" & harvest == "H1"), FUN = "mean", col = "orangered2", 
     main = "Original Reflectance - G3", ylim=c(0,0.7))
plot(subset(spec_org_data, field_id == "g4" & harvest == "H2"), FUN = "mean", col = "orange2", new = FALSE)
plot(subset(spec_org_data, field_id == "g4" & harvest == "H3"), FUN = "mean", col = "orange4", new = FALSE)
legend("topleft", legend = c("H1", "H2", "H3"),
       col = c("orangered2", "orange2", "orange4"), lty=1)


plot(subset(spec_nrm_data, field_id == "g4" & harvest == "H1"), FUN = "mean", col = "orangered2", 
     main = "Normalised Reflectance - G3", ylim=c(0,0.2))
plot(subset(spec_nrm_data, field_id == "g4" & harvest == "H2"), FUN = "mean", col = "orange2", new = FALSE)
plot(subset(spec_nrm_data, field_id == "g4" & harvest == "H3"), FUN = "mean", col = "orange4", new = FALSE)
legend("topleft", legend = c("H1", "H2", "H3"),
       col = c("orangered2", "orange2", "orange4"), lty=1)

par(mfrow=c(1,1))
```

# 4. Correlation with single bands

```{r cor analysis, echo=FALSE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%"}

## Correlation between reflectance vs N
cor_n_df <- hs_all_nrm_df[c(5:122, 131)] %>%
  corrr::correlate() %>% 
  corrr::focus(n)

cor_n_df$wv <- wv


## Correlation between reflectance vs ADF
cor_adf_df <- hs_all_nrm_df[c(5:122, 134)] %>%
  corrr::correlate() %>% 
  corrr::focus(adf)

cor_adf_df$wv <- wv


cor_df <- merge(cor_n_df[-1], cor_adf_df[-1])
cor_df_melt <- reshape2::melt(cor_df, id = "wv")
names(cor_df_melt) <- c("Wavelength", "Quality", "Correlation")

ggplot(cor_df_melt, aes(x = Wavelength, y = Correlation, group = Quality)) +
  geom_line(aes(color = Quality))+
  geom_point(aes(color = Quality)) + ylim(c(-1,1)) +
  theme_bw(base_size = 12, base_family = "Lucida") +
  scale_color_manual(values = c("#E48F1B", "#42858C"),
                    name = "Forage quality parameter", 
                    labels = c("Nitrogen (%)", "ADF (%)")) +
  labs(x = "Wavelength (nm)",
       y = "Correlation coefficient",
       caption = "Correlation coefficient with normalised spectral reflectance vs N (%) and ADF (%) (WIZ)") +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.caption = element_text(size = 11, face = "italic", hjust = 1),
    legend.position = "bottom"
  )
```

# 5. Linear regression models with normalised difference spectral indices (NDSI)

```{r ndsi, echo=FALSE, warning=FALSE, error=FALSE, message = FALSE, fig.align='center', out.width="100%"}

## Create NDSI for all possible bands

nri_data <- nri(spec_nrm_data, recursive = TRUE)
#nri_data

## Linear regression with NDSI vs N%

load("./lm_x_nri_wiz.RData")
#lm_n_nri <- lm.nri(nri_data ~ n, preddata = spec_nrm_data)
plot(lm_n_nri, coefficient = "r.squared", main = "NDSI vs N %",
     constraint = "p.value<0.05", colspace = "rgb", col = jcolors::jcolors("pal12"))
lines(c(480,950),c(480,950))

## Linear regression with NDSI vs ADF%

#lm_adf_nri <- lm.nri(nri_data ~ adf, preddata = spec_nrm_data)
plot(lm_adf_nri, coefficient = "r.squared", main = "NDSI vs ADF %",
     constraint = "p.value<0.05", colspace = "rgb", col = jcolors::jcolors("pal12"))
lines(c(480,950),c(480,950))

```